### ISSUE TITLE
platform.c - variables undeclared

### ISSUE THREAD

**Issue by friendlyFriend4000** [RJRP44/V53L5CX-Library#3]
I just bought the VL52L5CX-SATEL and I just want to test it out. Coming from arduino ide, it poses a challenge to me.

When I build an example or even an empty project with the library i get the following error:

managed_components/rjrp44__vl53l5cx/platform.c:22:74: error: 'ACK_CHECK_EN' undeclared (first use in this function)
   22 |     i2c_master_write_byte(cmd, (p_platform->address) | I2C_MASTER_WRITE, ACK_CHECK_EN);

this error follow ACK_VAL and NACK_VAL so that
ACK_CHECK_EN, NACK_VAL and ACK_VAL are undeclared. 

I am lost as to how to troubleshoot this. Blink and empty projects build and flash fine. Do you have any hints?

**Comment by RJRP44** [comment]
Hi @friendlyFriend4000, thanks for reporting this bug.
I've found the cause of this bug and will publish a fix by the end of the week.
Have a nice day.

**Comment by RJRP44** [comment]
@friendlyFriend4000, I've published a new version. Let me know if it worked for you.

**Comment by friendlyFriend4000** [comment]
> @friendlyFriend4000, I've published a new version. Let me know if it worked for you.

That fixed it. I am able to build it and flash it successfully. thank you very much. 

I hope you don't mind if I continue a different issue in this topic. I have a generic ESP32 dev board and in the ranging basic example I remapped the SDA and SCL pins to 21 and 22, as a result I get 'VL53L5CX not detected at requested address'. I have spent the whole night obsessively trying to get this to work to no avail. I2C scanner cannot find an address. Do you know of a method to check whether the sensor board is defective or not? Or any idea what esle I could try out. 

I have SDA and SCL pulled up to 3.3V.

**Comment by RJRP44** [comment]
> > @friendlyFriend4000, I've published a new version. Let me know if it worked for you.
> 
> That fixed it. I am able to build it and flash it successfully. thank you very much.
> 
> I hope you don't mind if I continue a different issue in this topic. I have a generic ESP32 dev board and in the ranging basic example I remapped the SDA and SCL pins to 21 and 22, as a result I get 'VL53L5CX not detected at requested address'. I have spent the whole night obsessively trying to get this to work to no avail. I2C scanner cannot find an address. Do you know of a method to check whether the sensor board is defective or not? Or any idea what esle I could try out.
> 
> I have SDA and SCL pulled up to 3.3V.

Is your VL53L5CX correctly wired? Can you share your wiring? I know I had a lot of issues at first but once you manage to set it up it works great.

**Comment by friendlyFriend4000** [comment]
@RJRP44 
> Is your VL53L5CX correctly wired? Can you share your wiring? I know I had a lot of issues at first but once you manage to set it up it works great.

I have it wired the same way you have with a few differences:

| VL53L5CX-SATEL Pins | ESP32S3 Pins                                  |           
|---------------------|-----------------------------------------------|
| INT                 | NC                                            |
| I2C_RST             | NC                                            |
| SDA                 | GPIO21, 2.5 kΩ pullup resistor to 3v3 |
| SCL                 | GPIO22, 2.5 kΩ pullup resistor to 3v3 |
| PWREN               | NC                                           |
| AVDD                | NC                                           |
| IOVDD               | 3V3                                           |
| GND                 | GND                                           |

With a multimeter i measure that PWREN is at 3.3V when IOVDD is powered by 3.3V and AVDD seems to lead to the 5V voltage regulator.

**Comment by RJRP44** [comment]
@friendlyFriend4000 
I forgot to mention that the LPn pin needs to be connected to 3V3 in order to enable I²C communications. You also need to connect AVDD to 3V3 because if you look closely to the VL53L5CX Satel schematic you will notice that the 3V3 for the sensor itself is only connected to AVDD through the regulator unless you solder SB1.

![image](https://github.com/RJRP44/VL53L5CX-Library/assets/52834078/ac93e9ab-64f2-4caf-9973-f969b0936f60)

Hope it works!

**Comment by friendlyFriend4000** [comment]
> @friendlyFriend4000 I forgot to mention that the LPn pin needs to be connected to 3V3 in order to enable I²C communications. You also need to connect AVDD to 3V3 because if you look closely to the VL53L5CX Satel schematic you will notice that the 3V3 for the sensor itself is only connected to AVDD through the regulator unless you solder SB1.
> 
> ![image](https://private-user-images.githubusercontent.com/52834078/290986895-ac93e9ab-64f2-4caf-9973-f969b0936f60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NDI2NDUsIm5iZiI6MTcwMjc0MjM0NSwicGF0aCI6Ii81MjgzNDA3OC8yOTA5ODY4OTUtYWM5M2U5YWItNjRmMi00Y2FmLTk5NzMtZjk2OWIwOTM2ZjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE1NTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OGE2N2JhZjBiODdhOGJiNTIyYzE3MzQ3ZDM2NDgzNDdiNzQ2YTVjMDE4NTkxNGMzYzAyYzRkMmQ1YjQ2YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qKEUn0gdz9aRzH7Htf_Ii94ZS-8YcSyfWkDMVqC-veE)
> 
> Hope it works!


It works! thank you so much. 
You are right, without AVDD it is not detected. That missing SB1 resistor did strike me as odd when I looked at it, I wish I found the actual schematics earlier, would have saved so much headache.
