### ISSUE TITLE
does this work on VL53L0X?

### ISSUE THREAD

**Issue by na3eddin** [RJRP44/V53L5CX-Library#4]
first thing i want to thank you from the buttom of my heart you really dont know what did this meant to me
anyway i am trying to work with [VL53L0X ](https://fr.aliexpress.com/item/1005006069135100.html?spm=a2g0o.order_list.order_list_main.22.6c9b5e5bMooLt3&gatewayAdapt=glo2fra)on esp32-S3.
i tried to make it work but all i get on terminal: VL53L5CX not detected at requested address.
i searched and changer the address (i know it's the same) just in case and i get the same error.
is there anything i can do?

**Comment by RJRP44** [comment]
Hi @na3eddin
VL53L0X and VL53L5CX are two distinct sensors from ST. They do share the same technology, but they are rather different. The VL53L0X can measure a single point up to 2m whereas the VL53L5CX is able to measure 64 points up to 4m. As a result, the firmware is very different and this library is not compatible with the VL53L0X so make to sure to check out dedicated libraries like this one [ESP32-VL53L0X](https://github.com/revk/ESP32-VL53L0X/tree/master) (i have not tested it).
Have a nice day

**Comment by na3eddin** [comment]
@RJRP44 heaven is filled with people like you thanks, i'll give it a try
