### ISSUE TITLE
Error in platform.c

### ISSUE THREAD

**Issue by pkepes** [RJRP44/V53L5CX-Library#5]
At line 90 you wrote:    `ret = i2c_master_cmd_begin(I2C_NUM_1, cmd, 1000 / portTICK_PERIOD_MS);` 
It would be nicer if instead of I2C_NUM_1, p_platform->port would be given like in the other functions. It caused big trouble, because I use I2C port 0.

**Comment by RJRP44** [comment]
Hi @pkepes, thanks for reporting this bug. It's true that I missed this one, sorry for the inconvenience, I'll post a new version tonight.
Have a nice day.

**Comment by RJRP44** [comment]
@pkepes, a new version is available : [vl53l5cx v2.0.4](https://components.espressif.com/components/rjrp44/vl53l5cx/versions/2.0.4). Let me know if it worked for you.

**Comment by pkepes** [comment]
Hello @RJRP44, it works fine now, thank you for the fast correction! I really appreciate your code.
